---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80